apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ingress
 namespace: about
spec:
 rules:
 - host: k8s-index.devopscoursewithbalakonda.xyz
   http:
     paths:
     - path: /about-svc.about.svc.cluster.local
       backend:
         serviceName: about-svc
         servicePort: 80